### ISSUE TITLE
LUTs.ijm missing semicolon in line 51

### ISSUE THREAD

**Issue by ghost** [BIOP/IPA4LSx#1]
I think there is a semicolon missing in line 51 of LUTs.ijm in BOIP/IPA4LSx/Week-02.

Current situation:

49	} else {
50		// exit
51		showNextLUT = false
52	}

Should be:

49	} else {
50		// exit
51		showNextLUT = false;
52	}

**Comment by NicoKiaru** [comment]
Thank you!
